openapi: 3.0.3
info:
  title: Todo AI Chatbot API
  description: |
    RESTful API for the Todo AI Chatbot system.
    All endpoints require JWT authentication via Better Auth.
  version: 1.0.0
  contact:
    name: Phase III Project

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.example.com
    description: Production

security:
  - bearerAuth: []

paths:
  /api/{user_id}/chat:
    post:
      summary: Send chat message
      description: |
        Single chat endpoint for all user interactions.
        The AI agent processes the message, calls MCP tools as needed,
        and returns a response.
      operationId: sendChatMessage
      tags:
        - Chat
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT sub claim)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            examples:
              addTask:
                summary: Add a task
                value:
                  message: "Add a task to buy groceries"
              listTasks:
                summary: List tasks
                value:
                  message: "Show me my tasks"
              completeTask:
                summary: Complete a task
                value:
                  message: "I finished buying groceries"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
              examples:
                taskAdded:
                  summary: Task added confirmation
                  value:
                    message: "I've added 'buy groceries' to your tasks!"
                    conversation_id: "550e8400-e29b-41d4-a716-446655440000"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Message cannot be empty"
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid or expired token"
        '403':
          description: Forbidden - User ID mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "You don't have permission to access this resource"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Something went wrong. Please try again later."

  /api/{user_id}/conversations:
    get:
      summary: Get conversation history
      description: Retrieve the user's conversation history
      operationId: getConversationHistory
      tags:
        - Conversations
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT sub claim)
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          description: Maximum number of messages to return
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Conversation history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationHistory'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check
      description: Check if the API is running
      operationId: healthCheck
      tags:
        - System
      security: []
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Better Auth JWT token

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: User's chat message
          minLength: 1
          maxLength: 10000
          example: "Add a task to buy groceries"

    ChatResponse:
      type: object
      required:
        - message
        - conversation_id
      properties:
        message:
          type: string
          description: AI assistant's response
          example: "I've added 'buy groceries' to your tasks!"
        conversation_id:
          type: string
          format: uuid
          description: Conversation identifier

    ConversationHistory:
      type: object
      required:
        - conversation_id
        - messages
      properties:
        conversation_id:
          type: string
          format: uuid
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      required:
        - id
        - role
        - content
        - created_at
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        created_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Human-readable error message

tags:
  - name: Chat
    description: Chat interaction endpoints
  - name: Conversations
    description: Conversation history management
  - name: System
    description: System health and status
